# https://taskfile.dev

version: '3'

vars:
  BIN_DIR: "{{.ROOT_DIR}}/bin"

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  show-root:
    cmds:
    - echo "{{.ROOT_DIR}}"
    - echo "{{.BIN_DIR}}"

  install-golangci-lint:
    dir: '{{.BIN_DIR}}'
    env:
      GOBIN: '{{.BIN_DIR}}'
    cmd: go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.1.6

  lint:
    cmds:
      - '{{.BIN_DIR}}/golangci-lint run ./... --config .golangci.pipeline.yaml'